### ISSUE TITLE
Add spaces to prefix and postfix outputs. 

### ISSUE THREAD

**Issue by Ryan-Awad** [raj457036/Simple-Tools#12]
When outputting a postfix and prefix expression, add spaces between numbers and operators. 

Ex: 
`4 + 2` (infix)

`4 2 +` (postfix)
`+ 4 2` (prefix) 

Instead of

`42+` (postfix)
`+42` (prefix)

# The reason:
For larger numbers, for example for the infix expression `342 + 723`, the postfix and prefix are `342723+` and `+342723`, respectively. This makes it impossible to know which two numbers are being summed. 

On another note, thank you for this tool! Helps me when studying!

**Comment by raj457036** [comment]
already has spaces!
<img width="435" alt="image" src="https://github.com/raj457036/Simple-Tools/assets/19155680/53c29738-ae0b-4938-8e2f-b71a71b7e9f9">

**Comment by Ryan-Awad** [comment]
> already has spaces!
> <img width="435" alt="image" src="https://github.com/raj457036/Simple-Tools/assets/19155680/53c29738-ae0b-4938-8e2f-b71a71b7e9f9">
> 
> <img width="431" alt="image" src="https://github.com/raj457036/Simple-Tools/assets/19155680/ff3a71e2-fcb2-47f2-b4d5-f164cd5a8956">
> 
> 

Oh hahah thank you!
I finished my course haha
