### ISSUE TITLE
Incorrect output for any expression containing $

### ISSUE THREAD

**Issue by mukundvijay123** [raj457036/Simple-Tools#16]
Pls fix your code for infix to postfix
'''
a$b$c--->abc $$
and not ab$c$
'''

**Comment by Nikunj-Mittal** [comment]
Yes, good issue pointed. The code doesn't seem to accommodate exponential operator. The correct answer is abc$$ where $ is the exp operator. @raj457036 Please fix this.

**Comment by raj457036** [comment]
Exponent symbol is "^" not "$" but its fixed and deployed.
