### ISSUE TITLE
Hello Raj In Infix to postfix and prefix conversion part, Result of prefix expression are not correct.

### ISSUE THREAD

**Issue by Vedbhanushali** [raj457036/Simple-Tools#3]
For Example take this infix expression - (A^B)/D*E/(F+A)*(D*E)-C
Your result :    /^AB/*DE-*+FA*DEC
actual result should be :   - * / * / ^ A B D E + F A * D E C

Reference of a converter site.
https://www.free-online-calculator-use.com/infix-to-prefix-converter.html

**Comment by raj457036** [comment]
Fixed the issue!

first below expression in wrong
(A^B)/DE/(F+A)(DE)-C

It should be 👇
(A^B)/D*E/(F+A)*(D*E)-C


For the site: that sites solution is wrong 😑 please try with real numbers and evaluate the result u will get my point.
