### ISSUE TITLE
major flow in infix to prefix convertor 

### ISSUE THREAD

**Issue by shubhamistic** [raj457036/Simple-Tools#5]
bro you have a major flow in your infix to prefix convertor 

suppose the infix notation is : (A-Z*(B+C)/D*E)+F
the expected prefix result should be : + - A * / * Z + B C D E F

but through your algorithm it is giving the result : +-A*Z/+BC*DEF

it is because when you traverse your code again you can see in prefix the same priority operator can be pushed without poping the existing operator so you need to fix this thing.

**Comment by raj457036** [comment]
Hello @shubhamistic, I am not very actively developing these tools anymore ( no time sorry 🥲). A PR would have been really appreciated.

Anyway thanks for bringing this up! I have fixed the logic for the preference of the operators and the issue is resolved. closing this for now.
