### ISSUE TITLE
Wrong output

### ISSUE THREAD

**Issue by MichaelScu** [raj457036/Simple-Tools#7]
![image](https://user-images.githubusercontent.com/111067946/218351303-983c2f33-10cb-441d-b1a4-802a975c7de9.png)

**Comment by raj457036** [comment]
Humm? And how is that! What were you expecting?

**Comment by raj457036** [comment]
![image](https://user-images.githubusercontent.com/19155680/219867949-26b5a1a9-2480-417c-a0f6-7a87a8cfb232.jpeg)

Evaluated prefix

![image](https://user-images.githubusercontent.com/19155680/219868040-d2eb1c83-860f-4584-8844-4281aec16093.jpeg)

Evaluated postfix

**Comment by raj457036** [comment]
Which output is wrong and how? And should have been the right output? Do explanation in detail before creating an issue.
