### ISSUE TITLE
Infix to Postfix convertor gives wrong output

### ISSUE THREAD

**Issue by mudit-51** [raj457036/Simple-Tools#9]
The algorithm used for the same is wrong. Try converting [a-b-c-d] and then try converting the output back to infix notation. It is easy to see that the potfix notation in the first place was wrong

**Comment by raj457036** [comment]
Add a screenshot! Please

**Comment by mudit-51** [comment]
<img width="491" alt="image" src="https://user-images.githubusercontent.com/118677956/221343623-5cfb2089-e8e1-4de0-b808-7f05e7d367f9.png">

Using your own infix->postfix tool, I get this as a result for [a-b-c-d]

<img width="503" alt="image" src="https://user-images.githubusercontent.com/118677956/221343639-2c840d4f-4213-4262-9bb3-0a4c00734ed1.png">

Plugging the answer into your own postfix->infix tool, we don't get the original equation. This convertor works perfectly, which leads me to conclude that the issue is with the infix->postfix convertor

**Comment by raj457036** [comment]
Thanks, @mudit-51 for bringing this up. I guess to fix the #5 I did miss some edge cases. I guess it has been fixed in the current version to tackle some extra edge cases which are not handled by the original algorithm so had to apply some modifications.

**Comment by raj457036** [comment]
Though this issue still persists for infix to prefix in the case where all the operator has
